#!/usr/bin/env bash
# Один раз на VPS: собирает /opt/runbonus/.env из backend/.env + Docker-поля.
# Не печатает значения секретов.
set -euo pipefail

BACKEND_ENV="${1:-}"
OUT="${2:-/opt/runbonus/.env}"

if [[ -z "$BACKEND_ENV" ]]; then
  for c in \
    /opt/runbonus/backend/.env \
    "$(cd "$(dirname "$0")/.." && pwd)/backend/.env"
  do
    if [[ -f "$c" ]]; then BACKEND_ENV="$c"; break; fi
  done
fi

[[ -n "$BACKEND_ENV" && -f "$BACKEND_ENV" ]] || {
  echo "Usage: $0 /path/to/backend/.env [/opt/runbonus/.env]" >&2
  exit 1
}

mkdir -p "$(dirname "$OUT")"
tmp="$(mktemp)"
# shellcheck disable=SC1090
set -a
source "$BACKEND_ENV"
set +a

DB_USER_VAL="${DB_USER:-runbonus}"
DB_PASS_VAL="${DB_PASSWORD:-}"
DB_NAME_VAL="${DB_NAME:-runbonus}"
ROOT_PASS_VAL="${MYSQL_ROOT_PASSWORD:-${DB_PASS_VAL}}"

{
  echo "# Generated by deploy/bootstrap-env-from-backend.sh — do not commit"
  echo "NODE_ENV=production"
  echo "PORT=3000"
  echo
  echo "MYSQL_DATABASE=${DB_NAME_VAL}"
  echo "MYSQL_USER=${DB_USER_VAL}"
  echo "MYSQL_PASSWORD=${DB_PASS_VAL}"
  echo "MYSQL_ROOT_PASSWORD=${ROOT_PASS_VAL}"
  echo
  echo "DB_HOST=mysql"
  echo "DB_PORT=3306"
  echo "DB_USER=${DB_USER_VAL}"
  echo "DB_PASSWORD=${DB_PASS_VAL}"
  echo "DB_NAME=${DB_NAME_VAL}"
  echo "REDIS_URL=redis://redis:6379"
  echo
  echo "JWT_SECRET=${JWT_SECRET:-}"
  echo "JWT_ADMIN_SECRET=${JWT_ADMIN_SECRET:-}"
  echo "PUBLIC_API_URL=${PUBLIC_API_URL:-https://runbonus.online}"
  echo "CORS_ORIGIN=${CORS_ORIGIN:-https://runbonus.online}"
  echo
  echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}"
  echo "TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}"
  echo "TELEGRAM_WEBHOOK_SECRET=${TELEGRAM_WEBHOOK_SECRET:-}"
  echo
  echo "SMS_LOGIN=${SMS_LOGIN:-}"
  echo "SMS_TOKEN=${SMS_TOKEN:-}"
  echo "SMS_SENDER=${SMS_SENDER:-RunBonus}"
  echo "SMS_SERVER=${SMS_SERVER:-https://api.osonsms.com}"
  echo "SMS_APP_HASH=${SMS_APP_HASH:-}"
  echo "SMS_TEST_PHONE=${SMS_TEST_PHONE:-}"
  echo "SMS_TEST_CODE=${SMS_TEST_CODE:-}"
  echo
  echo "OPENAI_API_KEY=${OPENAI_API_KEY:-}"
  echo "GEMINI_API_KEY=${GEMINI_API_KEY:-}"
  echo "FIREBASE_SERVICE_ACCOUNT_JSON=${FIREBASE_SERVICE_ACCOUNT_JSON:-}"
  echo "FIREBASE_SERVICE_ACCOUNT_PATH=${FIREBASE_SERVICE_ACCOUNT_PATH:-}"
} >"$tmp"

install -m 600 "$tmp" "$OUT"
rm -f "$tmp"
echo "[runbonus] wrote $OUT (from $BACKEND_ENV) — values not printed"
