ALTER TABLE workouts ADD COLUMN client_visible_map BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE workouts ADD COLUMN client_visible_limits BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE workouts ADD COLUMN background_tracking BOOLEAN NOT NULL DEFAULT TRUE;
